{
  "Biology": {
    "Cell Structure": [
      "What is the function of the mitochondria?",
      "What is the role of the nucleus?",
      "Name three organelles found in plant cells but not animal cells.",
      "What is the function of ribosomes?",
      "Define cytoplasm.",
      "What is the function of the cell membrane?",
      "What is the role of chloroplasts?",
      "What is the function of the vacuole in plant cells?",
      "What is the difference between eukaryotic and prokaryotic cells?",
      "What is the function of the Golgi apparatus?",
      "What is the function of the endoplasmic reticulum?",
      "What is the function of lysosomes?",
      "What is the cell wall made of in plants?",
      "What is the function of the nucleolus?",
      "What is the function of centrioles?",
      "What is the function of the cytoskeleton?",
      "What is the function of the plasma membrane?",
      "What is the function of vesicles?",
      "What is the function of peroxisomes?",
      "What is the function of the smooth ER?"
    ],
    "Enzymes": [
      "What is an enzyme?",
      "What is the active site?",
      "What is meant by enzyme specificity?",
      "How does temperature affect enzyme activity?",
      "How does pH affect enzyme activity?",
      "What is denaturation?",
      "What is a substrate?",
      "What is the enzyme–substrate complex?",
      "What is the lock-and-key model?",
      "What is the induced-fit model?",
      "What is an inhibitor?",
      "What is a competitive inhibitor?",
      "What is a non-competitive inhibitor?",
      "What is activation energy?",
      "How do enzymes lower activation energy?",
      "What is an optimum temperature?",
      "What is an optimum pH?",
      "What is a cofactor?",
      "What is a coenzyme?",
      "What is a metabolic pathway?"
    ],
    "Respiration": [
      "What is respiration?",
      "What is the difference between aerobic and anaerobic respiration?",
      "Write the word equation for aerobic respiration.",
      "Write the word equation for anaerobic respiration in animals.",
      "Where does aerobic respiration occur?",
      "Where does anaerobic respiration occur?",
      "What is ATP?",
      "Why is ATP important?",
      "What is glycolysis?",
      "What is the Krebs cycle?",
      "What is the electron transport chain?",
      "What is oxygen debt?",
      "What is lactic acid?",
      "Why do muscles fatigue?",
      "What is fermentation?",
      "What is the role of mitochondria in respiration?",
      "What is oxidative phosphorylation?",
      "What is the role of enzymes in respiration?",
      "What is the role of glucose in respiration?",
      "What is the role of oxygen in aerobic respiration?"
    ]
  },

  "Chemistry": {
    "Atomic Structure": [
      "What is an atom?",
      "What are the three subatomic particles?",
      "What is the charge of a proton?",
      "What is the charge of an electron?",
      "What is the charge of a neutron?",
      "Where are protons located?",
      "Where are electrons located?",
      "Where are neutrons located?",
      "What is the atomic number?",
      "What is the mass number?",
      "What are isotopes?",
      "What is an ion?",
      "What is a cation?",
      "What is an anion?",
      "What is an electron shell?",
      "What is the maximum number of electrons in the first shell?",
      "What is the maximum number of electrons in the second shell?",
      "What is the relative mass of a proton?",
      "What is the relative mass of an electron?",
      "What is the relative mass of a neutron?"
    ],
    "Bonding": [
      "What is ionic bonding?",
      "What is covalent bonding?",
      "What is metallic bonding?",
      "What is a molecule?",
      "What is a compound?",
      "What is an ionic lattice?",
      "Why do ionic compounds have high melting points?",
      "Why do ionic compounds conduct electricity when molten?",
      "What is a single covalent bond?",
      "What is a double covalent bond?",
      "What is a triple covalent bond?",
      "What is a polar covalent bond?",
      "What is electronegativity?",
      "What is a metallic lattice?",
      "Why are metals good conductors?",
      "Why are metals malleable?",
      "What is a giant covalent structure?",
      "Give an example of a giant covalent structure.",
      "What is hydrogen bonding?",
      "What is an intermolecular force?"
    ],
    "Acids & Bases": [
      "What is an acid?",
      "What is a base?",
      "What is an alkali?",
      "What is the pH scale?",
      "What is a neutral solution?",
      "What ion do acids produce in water?",
      "What ion do alkalis produce in water?",
      "What is neutralisation?",
      "Write the word equation for acid + base.",
      "Write the word equation for acid + metal.",
      "Write the word equation for acid + carbonate.",
      "What is an indicator?",
      "What colour does litmus turn in acid?",
      "What colour does litmus turn in alkali?",
      "What is a strong acid?",
      "What is a weak acid?",
      "What is a strong alkali?",
      "What is a weak alkali?",
      "What is titration?",
      "What is a salt?"
    ]
  },

  "Physics": {
    "Motion": [
      "What is speed?",
      "What is velocity?",
      "What is acceleration?",
      "What is deceleration?",
      "What is displacement?",
      "What is distance?",
      "What is the formula for speed?",
      "What is the formula for acceleration?",
      "What is uniform motion?",
      "What is non-uniform motion?",
      "What is a distance–time graph?",
      "What is a velocity–time graph?",
      "What does the gradient of a distance–time graph represent?",
      "What does the gradient of a velocity–time graph represent?",
      "What does the area under a velocity–time graph represent?",
      "What is terminal velocity?",
      "What is free fall?",
      "What is friction?",
      "What is relative velocity?",
      "What is instantaneous speed?"
    ],
    "Forces": [
      "What is a force?",
      "What is the unit of force?",
      "What is weight?",
      "What is mass?",
      "What is gravity?",
      "What is friction?",
      "What is air resistance?",
      "What is tension?",
      "What is compression?",
      "What is upthrust?",
      "What is a balanced force?",
      "What is an unbalanced force?",
      "What is Newton’s First Law?",
      "What is Newton’s Second Law?",
      "What is Newton’s Third Law?",
      "What is resultant force?",
      "What is pressure?",
      "What is the formula for pressure?",
      "What is density?",
      "What is the formula for density?"
    ],
    "Waves": [
      "What is a wave?",
      "What is a transverse wave?",
      "What is a longitudinal wave?",
      "What is amplitude?",
      "What is wavelength?",
      "What is frequency?",
      "What is wave speed?",
      "What is the formula for wave speed?",
      "What is reflection?",
      "What is refraction?",
      "What is diffraction?",
      "What is interference?",
      "What is the electromagnetic spectrum?",
      "What is a sound wave?",
      "What is ultrasound?",
      "What is infrasound?",
      "What is resonance?",
      "What is a medium?",
      "What is a crest?",
      "What is a trough?"
    ]
  },

  "Maths": {
    "Algebra": [
      "What is a variable?",
      "What is a coefficient?",
      "What is an expression?",
      "What is an equation?",
      "What is a linear equation?",
      "What is a quadratic equation?",
      "What is a polynomial?",
      "What is factorisation?",
      "What is expansion?",
      "What is substitution?",
      "What is a term?",
      "What is a constant?",
      "What is simultaneous equations?",
      "What is an inequality?",
      "What is a function?",
      "What is a sequence?",
      "What is the nth term?",
      "What is an arithmetic sequence?",
      "What is a geometric sequence?",
      "What is a ratio?"
    ],
    "Geometry": [
      "What is a point?",
      "What is a line?",
      "What is a ray?",
      "What is an angle?",
      "What is a triangle?",
      "What is a quadrilateral?",
      "What is a polygon?",
      "What is a circle?",
      "What is the radius?",
      "What is the diameter?",
      "What is the circumference?",
      "What is the area of a triangle?",
      "What is the area of a circle?",
      "What is the Pythagorean theorem?",
      "What is a right angle?",
      "What is an acute angle?",
      "What is an obtuse angle?",
      "What is a reflex angle?",
      "What is a parallel line?",
      "What is a perpendicular line?"
    ],
    "Trigonometry": [
      "What is sine?",
      "What is cosine?",
      "What is tangent?",
      "What is SOHCAHTOA?",
      "What is a right triangle?",
      "What is the hypotenuse?",
      "What is the opposite side?",
      "What is the adjacent side?",
      "What is the sine rule?",
      "What is the cosine rule?",
      "What is a radian?",
      "What is a degree?",
      "What is the unit circle?",
      "What is a trigonometric ratio?",
      "What is an angle of elevation?",
      "What is an angle of depression?",
      "What is periodicity?",
      "What is amplitude in trig graphs?",
      "What is the period of a trig function?",
      "What is a phase shift?"
    ]
  }
}
